### ISSUE TITLE
loading h5 embeding file in train.py is killed due to large memory  requirement

### ISSUE THREAD

**Issue by jiyanbio** [samsledje/D-SCRIPT#11]
in train.py:
    print(f"# Loading embeddings", file=output)
    tensors = {}
    all_proteins = set(train_n0).union(set(train_n1)).union(set(test_n0)).union(set(test_n1))
    for prot_name in tqdm(all_proteins):
        **tensors[prot_name] = torch.from_numpy(h5fi[prot_name][:, :])**

Can it be modified with pytorch dataloader?

**Comment by jiyanbio** [comment]
Even this very small dataset for test, the train.py also reported error message as follows:

dscript train --train train.pairSeq.txt --val test.pairSeq.txt --embedding merge.h5 
# Called as: /usr/local/bin/dscript train --train train.pairSeq.txt --val test.pairSeq.txt --embedding merge.h5
# Using CPU
# Loading training pairs from train.pairSeq.txt...
# Loading testing pairs from test.pairSeq.txt...
# Loading embeddings
100%|############################################################################| 535/535 [00:13<00:00, 40.49it/s]
# Initializing embedding model with:
        projection_dim: 100
        dropout_p: 0.5
# Initializing contact model with:
        hidden_dim: 50
        kernel_width: 7
# Initializing interaction model with:
        pool_width: 9
        use_w: False
ModelInteraction(
  (activation): LogisticActivation()
  (embedding): FullyConnectedEmbed(
    (transform): Linear(in_features=6165, out_features=100, bias=True)
    (drop): Dropout(p=0.5, inplace=False)
    (activation): ReLU()
  )
  (contact): ContactCNN(
    (hidden): FullyConnected(
      (conv): Conv2d(200, 50, kernel_size=(1, 1), stride=(1, 1))
      (batchnorm): BatchNorm2d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (activation): ReLU()
    )
    (conv): Conv2d(50, 1, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3))
    (batchnorm): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activation): Sigmoid()
  )
  (maxPool): MaxPool2d(kernel_size=9, stride=9, padding=4, dilation=1, ceil_mode=False)
)
# Using save prefix "2021-03-23-22-14"
# Training with Adam: lr=0.001, weight_decay=0
        num_epochs: 100
        epoch_scale: 5
        batch_size: 25
        interaction weight: 0.35
        contact map weight: 0.65
Epoch 1/100:   0%|                                                                           | 0/8 [00:00<?, ?it/s]python3: /pytorch/third_party/ideep/mkl-dnn/src/common/memory_tracking.hpp:240: void* mkldnn::impl::memory_tracking::registry_t::get(const key_t&, void*) const: Assertion `size() == 0' failed.
Aborted

**Comment by jiyanbio** [comment]
When using a small size of dataset as input, the train.py further report errors as follows.

dscript train --train train.pairSeq.txt --val test.pairSeq.txt --embedding merge.h5 -d 0
# Called as: /usr/local/bin/dscript train --train train.pairSeq.txt --val test.pairSeq.txt --embedding merge.h5 -d 0
# Using CUDA device 0 - GRID P40-6C
# Loading training pairs from train.pairSeq.txt...
# Loading testing pairs from test.pairSeq.txt...
# Loading embeddings
100%|############################################################################| 535/535 [00:12<00:00, 42.09it/s]
# Initializing embedding model with:
        projection_dim: 100
        dropout_p: 0.5
# Initializing contact model with:
        hidden_dim: 50
        kernel_width: 7
# Initializing interaction model with:
        pool_width: 9
        use_w: False
ModelInteraction(
  (activation): LogisticActivation()
  (embedding): FullyConnectedEmbed(
    (transform): Linear(in_features=6165, out_features=100, bias=True)
    (drop): Dropout(p=0.5, inplace=False)
    (activation): ReLU()
  )
  (contact): ContactCNN(
    (hidden): FullyConnected(
      (conv): Conv2d(200, 50, kernel_size=(1, 1), stride=(1, 1))
      (batchnorm): BatchNorm2d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (activation): ReLU()
    )
    (conv): Conv2d(50, 1, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3))
    (batchnorm): BatchNorm2d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (activation): Sigmoid()
  )
  (maxPool): MaxPool2d(kernel_size=9, stride=9, padding=4, dilation=1, ceil_mode=False)
)
# Using save prefix "2021-03-23-22-17"
# Training with Adam: lr=0.001, weight_decay=0
        num_epochs: 100
        epoch_scale: 5
        batch_size: 25
        interaction weight: 0.35
        contact map weight: 0.65
Epoch 1/100:   0%|                                                                           | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/dscript", line 11, in <module>
    load_entry_point('dscript==0.1.3', 'console_scripts', 'dscript')()
  File "/usr/local/lib/python3.6/site-packages/dscript-0.1.3-py3.6.egg/dscript/__main__.py", line 54, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/dscript-0.1.3-py3.6.egg/dscript/commands/train.py", line 470, in main
    loss, correct, mse, b = interaction_grad(model, z0, z1, y, tensors, use_cuda, weight=inter_weight)
  File "/usr/local/lib/python3.6/site-packages/dscript-0.1.3-py3.6.egg/dscript/commands/train.py", line 221, in interaction_grad
    c_map_mag, p_hat = predict_cmap_interaction(model, n0, n1, tensors, use_cuda)
  File "/usr/local/lib/python3.6/site-packages/dscript-0.1.3-py3.6.egg/dscript/commands/train.py", line 190, in predict_cmap_interaction
    cm, ph = model.map_predict(z_a, z_b)
  File "/usr/local/lib/python3.6/site-packages/dscript-0.1.3-py3.6.egg/dscript/models/interaction.py", line 159, in map_predict
    C = self.cpred(z0, z1)
  File "/usr/local/lib/python3.6/site-packages/dscript-0.1.3-py3.6.egg/dscript/models/interaction.py", line 143, in cpred
    B = self.contact.broadcast(e0, e1)
  File "/usr/local/lib/python3.6/site-packages/dscript-0.1.3-py3.6.egg/dscript/models/contact.py", line 115, in broadcast
    B = self.hidden(z0, z1)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dscript-0.1.3-py3.6.egg/dscript/models/contact.py", line 49, in forward
    z_mul = z0.unsqueeze(3) * z1.unsqueeze(2)
RuntimeError: CUDA out of memory. Tried to allocate 74.00 MiB (GPU 0; 5.97 GiB total capacity; 4.74 GiB already allocated; 64.86 MiB free; 4.95 GiB reserved in total by PyTorch)

**Comment by samsledje** [comment]
Hi Jiyan,

Feel free to modify the source code as you see fit to play around with it -- I find it's usually easier to pre-load the embeddings from a runtime point of view, but if you're running into memory constraints. One thing I've thought about adding is a flag for whether to pre-load the data or not. Let me know if this would be helpful!

With regard to the GPU memory issue, that's usually caused when one (or both) of the protein sequences is too long, so the computation graph doesn't fit within GPU memory constraints. In the paper, we limited training to sequences <=800 AA.

**Comment by jiyanbio** [comment]
> Hi Jiyan,
> 
> Feel free to modify the source code as you see fit to play around with it -- I find it's usually easier to pre-load the embeddings from a runtime point of view, but if you're running into memory constraints. One thing I've thought about adding is a flag for whether to pre-load the data or not. Let me know if this would be helpful!
> 
> With regard to the GPU memory issue, that's usually caused when one (or both) of the protein sequences is too long, so the computation graph doesn't fit within GPU memory constraints. In the paper, we limited training to sequences <=800 AA.

But, after embeding sequences, the size of h5 files is 2000G. It's too huge to run on any machine.

**Comment by samsledje** [comment]
How many sequences are you trying to embed? I've done up to 20,000 and it doesn't take more than a few hundred GB. I can definitely work on adding functionality to load or compute each embedding in place, but this will of course slow down the training time.

**Comment by rs239** [comment]
Hi Jiyan,
 Sam and I have discussed how to speed up the embedding access and, like
Sam mentioned, we can make a change to load them one at a time or do them
in batches. These choices will have different tradeoffs in terms of runtime
and memory requirements. Just so we can understand your use-case, would you
be ok sharing the max and avg length of your sequences, and the number of
sequences?

thanks
-r

**Comment by jiyanbio** [comment]
- the number of sequenes is about 200,000 most of which is shorter than 800 bp.  
- I will exclude some longer seqences. 
- Moreover, even for 20,000 sequences as input, it was ran out of memory on my machine. So, if the trainp.py could handle 5~10 h5 files, It will be much more convenient for users to test it on different datasets.

**Comment by rs239** [comment]
Hi Jiyan,
 Yes, the idea of splitting training data into chunks makes sense. We'll
think about how best to set this up and will keep you posted.

thanks
-r

**Comment by jiyanbio** [comment]
Thank you!  Could you tell me when the updated version for handling multiples hdf5 files will be online?

**Comment by samsledje** [comment]
Hi Jiyan,

I don't think we'll have the bandwidth to fix this for the next few weeks, at least. If you'd like to submit a pull request we'd be happy to take a look at it.
