### ISSUE TITLE
SkipLTSM  object has no attribute 'map_predict'

### ISSUE THREAD

**Issue by 777moneymaker** [samsledje/D-SCRIPT#27]
```
python3 -m dscript predict --pairs pairs_known.tsv --seqs experimentally_known/all.fasta --model models/lm_v1.sav --outfile known_predictions.txt
# Using CPU
# Generating Embeddings...
  0%|                                                                                                                                                                               | 0/6 [00:00<?, ?it/s]Downloading model lm_v1 from http://cb.csail.mit.edu/cb/dscript/data/models/dscript_lm_v1.pt...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [02:00<00:00, 20.02s/it]
# Making Predictions...
  0%|                                                                                                                                                                               | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/dscript-0.1.6-py3.7.egg/dscript/__main__.py", line 58, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/dscript-0.1.6-py3.7.egg/dscript/__main__.py", line 54, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/dscript-0.1.6-py3.7.egg/dscript/commands/predict.py", line 146, in main
    cm, p = model.map_predict(p0, p1)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'SkipLSTM' object has no attribute 'map_predict'
```

**Comment by samsledje** [comment]
Hi Miłosz, Could you add a bit more information about which version of D-SCRIPT you're running, how you installed it, and what inputs you're using? Thanks!
