### ISSUE TITLE
'collections.OrderedDict' object has no attribute cuda

### ISSUE THREAD

**Issue by Moeinh77** [samsledje/D-SCRIPT#49]
Hi @samsledje , so I tried doing the prediction through the command line this time but I'm having an issue that I was hoping you can help me with. I am running ```dscript predict --pairs ecoli_test.tsv --model dscript_human_v2.pt --seqs ecoli.fasta --device 0``` but I'm getting
 ```[2023-05-11-10:07:28] Using CUDA device 0 - NVIDIA GeForce RTX 3080 Ti
[2023-05-11-10:07:28] Loading model from dscript_human_v2.pt
Traceback (most recent call last):
  File "/home/jlw742/pytorch/bin/dscript", line 33, in <module>
    sys.exit(load_entry_point('dscript==0.2.2', 'console_scripts', 'dscript')())
  File "/home/jlw742/pytorch/lib/python3.9/site-packages/dscript-0.2.2-py3.9.egg/dscript/__main__.py", line 65, in main
    args.func(args)
  File "/home/jlw742/pytorch/lib/python3.9/site-packages/dscript-0.2.2-py3.9.egg/dscript/commands/predict.py", line 105, in main
    model = torch.load(modelPath).cuda()
AttributeError: 'collections.OrderedDict' object has no attribute 'cuda' 
```
I did some research and apparently the issue is that the weights of the model were saved as state_dict but now they are being loaded by the```torch.load()``` method instead of the ```model.load_state_dict```. 
I have downloaded the ```dscript_human_v2.pt``` weight and I am using the ecoli files from your repo.
Would you mind helping me with this? Thank you very much

**Comment by Moeinh77** [comment]
Oh I realized my mistake I should use the .sav files with the command line and .pt files with the build method. The issue is solved!
