### ISSUE TITLE
TT3D - error at beginning of making predictions

### ISSUE THREAD

**Issue by twaksman001** [samsledje/D-SCRIPT#55]
I have run TT non-3D with no problems, but TT3D has generated this error.

**output log file printed text**

[2023-09-10-10:42:43] Using CPU
[2023-09-10-10:42:43] Loading model from /cluster/jb_lab/twaksman001/Bioinformatics/Interaction Prediction/D-SCRIPT/tt3d_v1.sav
[2023-09-10-10:42:43] Loading pairs from /cluster/jb_lab/twaksman001/Bioinformatics/Interaction Prediction/D-SCRIPT/Mp Effectors At Proteome TT3D/Pairs_MpEffectors_AtProteome_TT3D_1.txt
[2023-09-10-10:42:43] Generating Embeddings...
[2023-09-10-11:35:02] Loading FoldSeek 3Di sequences...
[2023-09-10-11:35:02] Making Predictions...

**error log file printed text**

_(end of generating embeddings)_
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2370/2370 [52:18<00:00,  1.32s/it]

  0%|          | 0/163229 [00:00<?, ?it/s]
  0%|          | 0/163229 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/cluster/jb_lab/twaksman001/conda/envs/bio1/bin/dscript", line 8, in <module>
    sys.exit(main())
  File "/cluster/jb_lab/twaksman001/conda/envs/bio1/lib/python3.9/site-packages/dscript/__main__.py", line 77, in main
    args.func(args)
  File "/cluster/jb_lab/twaksman001/conda/envs/bio1/lib/python3.9/site-packages/dscript/commands/predict.py", line 221, in main
    cm, p = model.map_predict(
  File "/cluster/jb_lab/twaksman001/conda/envs/bio1/lib/python3.9/site-packages/dscript/models/interaction.py", line 219, in map_predict
    (self.xx[:N] + 1 - ((N + 1) / 2)) / (-1 * ((N + 1) / 2))
  File "/cluster/jb_lab/twaksman001/conda/envs/bio1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModelInteraction' object has no attribute 'xx'

**Comment by samsledje** [comment]
Thanks for bringing this to our attention, this should be fixed now! Please re-download the model from http://cb.csail.mit.edu/cb/dscript/data/models/tt3d_v1.sav.
