### ISSUE TITLE
ModuleNotFoundError when trying to unload pretrained TT3D model

### ISSUE THREAD

**Issue by SarahND97** [samsledje/D-SCRIPT#60]
Hi! 
I'm trying to use the pretrained TT3D model when evaluating a test set of mine. However, after having downloaded it from, https://d-script.readthedocs.io/en/stable/data.html, I get the following error when using evaluate: 

```
Traceback (most recent call last):
  File "dscript/commands/evaluate.py", line 283, in <module>
    main(parser.parse_args())
  File "dscript/commands/evaluate.py", line 200, in main
    model = torch.load(model_path).cuda()
  File "/home/sarahn/miniconda3/envs/dscript/lib/python3.7/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/sarahn/miniconda3/envs/dscript/lib/python3.7/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/home/sarahn/miniconda3/envs/dscript/lib/python3.7/site-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'dscript'
```
Do you have any idea how this could be fixed? Has anybody been able to successfully use the pretrained TT3D model? I have installed `dscript` with pip.

**Comment by samsledje** [comment]
Hi Sarah,

I'm unable to replicate this-- can you please post the full `dscript evaluate` command that you're running, along with a `pip freeze` or `env.yml` file to recreate your environment?

Thanks,
Sam

**Comment by SarahND97** [comment]
Hi! 
Sorry for the late reply. 
The full evaluate command is the following: 
` python3 dscript/commands/evaluate.py --test ../../D-SCRIPT/data/pairs/human_pairs_dscript.tsv --foldseek_fasta fseek_seqs.fasta -o test_fseek_12_12_23_1.out --embedding super_human_embed.h5 --model dscript/commands/tt3d_v1.sav -d 0`
I'm running it with python to be able to modify the file easily. 

The contents of my env.yml files are the following: 
```
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - pip=20.0
  - cudatoolkit=11.3 #original 10.2
  - python=3.7
  - pytorch=1.11
  - biopython
  - h5py
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - tqdm
```
The output of `pip freeze` is the following: 
```
attrs==19.3.0
Automat==0.8.0
biopython==1.80
blinker==1.4
blosc2==2.0.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==23.3.1
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
contourpy==1.0.7
cryptography==2.8
cupshelpers==1.0
cycler==0.11.0
Cython==0.29.33
dbus-python==1.2.16
defer==1.0.6
dill==0.3.6
distro==1.4.0
distro-info==0.23+ubuntu1.1
dscript==0.2.6
entrypoints==0.3
fail2ban==0.11.1
fonttools==4.38.0
h5py==3.7.0
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
Jinja2==2.10.1
joblib==1.2.0
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
kiwisolver==1.4.4
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
macaroonbakery==1.3.1
MarkupSafe==1.1.0
matplotlib==3.6.3
more-itertools==4.2.0
msgpack==1.0.4
netifaces==0.10.4
numexpr==2.8.4
numpy==1.24.1
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.1.0
packaging==23.0
pandas==1.5.3
patsy==0.5.3
pexpect==4.6.0
Pillow==9.4.0
protobuf==3.6.1
py-cpuinfo==9.0.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycups==1.9.73
pyfunctional==1.4.3
Pygments==2.3.1
PyGObject==3.36.0
PyHamcrest==1.9.0
pyinotify==0.9.6
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==3.0.9
pyRFC3339==1.1
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.8.2
python-debian==0.1.36+ubuntu1.1
pytz==2022.7.1
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
scikit-learn==1.2.0
scipy==1.10.0
screen-resolution-extra==0.0.0
seaborn==0.12.2
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sklearn==0.0.post1
sklearn-utils==0.0.15
sos==4.5.6
ssh-import-id==5.10
statsmodels==0.13.5
systemd-python==234
tables==3.8.0
tabulate==0.9.0
threadpoolctl==3.1.0
torch==1.13.1
tqdm==4.64.1
Twisted==18.9.0
typing_extensions==4.4.0
ubuntu-advantage-tools==8001
unattended-upgrades==0.1
urllib3==1.25.8
wadllib==1.3.3
xkit==0.0.0
zipp==1.0.0
zope.interface==4.7.1
```

**Comment by samsledje** [comment]
I would make sure that the `python3` executable you are running is part of the same conda environment `which python`, and check that you are able to import dscript from the interpreter (`python; import dscript`). This seems like an issue with the environment.

**Comment by SarahND97** [comment]
Ah ok thank you!
