### ISSUE TITLE
Can't get attribute '_rebuild_parameter_with_state'

### ISSUE THREAD

**Issue by Rohit-Satyam** [samsledje/D-SCRIPT#66]
Hi @rs239 @samsledje @merterden98 @Kapil-Devkota 

While running dscript locally I get the following error

```
[2024-04-01-18:50:34] Using CPU
[2024-04-01-18:50:34] Loading model from topsy_turvy_v1.sav
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/dscript/bin/dscript", line 8, in <module>
    sys.exit(main())
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/dscript/__main__.py", line 77, in main
    args.func(args)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/dscript/commands/predict.py", line 119, in main
    modelPath, map_location=torch.device("cpu")
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/torch/serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute '_rebuild_parameter_with_state' on <module 'torch._utils' from '/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/torch/_utils.py'>

```

How can I resolve it?

**Comment by merterden98** [comment]
Could you provide the command you ran? I will attempt to reproduce this locally and get back to you.

**Comment by samsledje** [comment]
Hi @Rohit-Satyam , I believe we had an issue with model versioning. Could you please retry downloading the topsy-turvy model from `http://cb.csail.mit.edu/cb/dscript/data/models/topsy_turvy_v1.sav` and try again? Pleaes also let us know what version of `torch` and what version of `dscript` you are running, as well as which command you are running.

**Comment by Rohit-Satyam** [comment]
Hi @samsledje 

I installed dscript as follows: 

```
conda env create --file environment.yml
pip install dscript
```

so `'pytorch=1.11'`

```
Looking for: ['pip=20.0', 'cudatoolkit=10.2', 'python=3.7', 'pytorch=1.11', 'biopython', 'h5py', 'matplotlib', 'numpy', 'pandas', 'scikit-learn', 'scipy', 'seaborn', 'setuptools', 'tqdm']
```

**Comment by Rohit-Satyam** [comment]
> Hi @Rohit-Satyam , I believe we had an issue with model versioning. Could you please retry downloading the topsy-turvy model from `http://cb.csail.mit.edu/cb/dscript/data/models/topsy_turvy_v1.sav` and try again? Pleaes also let us know what version of `torch` and what version of `dscript` you are running, as well as which command you are running.

This works. So I will close this issue.

**Comment by Rohit-Satyam** [comment]
Sorry one last query. The result I get are different from the topsy-turvy mode used when running the script online.

```
##From script webserver
ProtA ProtB 0.395801723003387
ProtB ProtC 0.012149082496762
ProtA ProtC 0.006960090249777
ProtB ProtA 0.395799666643143

#from command line
ProtC   ProtA   0.04700227454304695
ProtA   ProtB   0.46136778593063354
ProtB   ProtC   0.09835360199213028
ProtA   ProtC   0.047002099454402924
ProtB   ProtA   0.46136853098869324
```

Though both the results say that ProtA and ProtB have more physical affinity, the values are greater on CLI. Should I be worried?

**Comment by Rohit-Satyam** [comment]
I was also wondering if I can use `Human TT3D model`  if its performance is better than `topsy-turvy`

**Comment by Rohit-Satyam** [comment]
I am experiencing another error. So I have 5K pairwise comparison and since I am running dscript on CPU, I thought to split my pairwise.tsv into small parts and run these parts parallel


```bash
ls -1 split_file/splt_* | parallel -j 2 "dscript predict --pairs {} --seqs reformatted.fasta --model topsy_turvy_v1.sav -o {}.dscript"
k[2024-04-04-10:51:15] Using CPU
[2024-04-04-10:51:15] Loading model from topsy_turvy_v1.sav
[2024-04-04-10:51:15] Loading pairs from split_file/splt_aa.dscript.cmaps.h5
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/dscript/bin/dscript", line 8, in <module>
    sys.exit(main())
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/dscript/__main__.py", line 77, in main
    args.func(args)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/dscript/commands/predict.py", line 138, in main
    pairs = pd.read_csv(csvPath, sep="\t", header=None)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 745, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
[2024-04-04-10:51:24] Using CPU
[2024-04-04-10:51:24] Loading model from topsy_turvy_v1.sav
[2024-04-04-10:51:24] Loading pairs from split_file/splt_aa.dscript.log
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/dscript/bin/dscript", line 8, in <module>
    sys.exit(main())
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/dscript/__main__.py", line 77, in main
    args.func(args)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/dscript/commands/predict.py", line 139, in main
    all_prots = set(pairs.iloc[:, 0]).union(set(pairs.iloc[:, 1]))
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/core/indexing.py", line 1506, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/core/indexing.py", line 754, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/core/indexing.py", line 1409, in _validate_key
    self._validate_integer(key, axis)
  File "/home/subudhak/miniconda3/envs/dscript/lib/python3.7/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
[2024-04-04-10:51:32] Using CPU
[2024-04-04-10:51:32] Loading model from topsy_turvy_v1.sav
[2024-04-04-10:51:32] Loading pairs from split_file/splt_aa.dscript.positive.tsv
[2024-04-04-10:51:32] Generating Embeddings...
[2024-04-04-11:18:43] Making Predictions...
100%|██████████| 287/287 [27:10<00:00,  5.68s/it]
100%|██████████| 578/578 [06:29<00:00,  1.48it/s]
```

**Comment by merterden98** [comment]
Hey Rohit, I can't make much comment on the online version compared to the local install but I can comment on the other 2. The Human TT-3D model requires additional knowledge of 3DI information given by foldseek. You can still run it, but you need to have pdb files that match the proteins of interest. Your second error seems to be coming from pandas, perhaps there's something going on with the contents of that directory, it is hard to say as the globbing could be messing things up. The `.positive.` files are a convenience for filtering for positive prediction pairs. The `--thresh` flag for the predict command will only keep pairs that have at least a score of whatever thresh is set to in the output file.
